<?php

namespace Tests\Feature\Http\Contollers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class HomeContollerTest extends TestCase
{
    use RefreshDatabase;
    protected function setUp(): void {
        parent::setUp(); // TODO: Change the autogenerated stub
        //$this->withoutMiddleware(['check.ban', 'auth', 'ban.page']);
    }

    /**
     * A basic feature test example.
     */
    public function test_home_index_view(): void
    {
        $response = $this->get('/');

        $response->assertStatus(200)
        ->assertViewIs('post.index');
    }
    public function test_home_contacts_view(): void
    {
        $response = $this->get('/contacts');

        $response->assertStatus(200)
        ->assertViewIs('home.contacts');
    }
    public function test_home_about_view(): void
    {
        $response = $this->get('/about');
        $response->assertStatus(200)
            ->assertViewIs('home.about');
    }
}
